### ISSUE TITLE
Busybox

### ISSUE THREAD

**Issue by kronkinatorix** [V3rB0se/Alynx-Nethunter#1]
Not sure if this will get an answer given that the repo is aging - nethunter seems to require the installation of busybox but as near as I can tell this is impossible on Android 12/13. I've seen that you've put together kernels for nethunter on Android 12/3 though and I'm at a a loss as to how this contradiction can be resolved. Any guidance will be appreciated :)

**Comment by V3rB0se** [comment]
> Not sure if this will get an answer given that the repo is aging - nethunter seems to require the installation of busybox but as near as I can tell this is impossible on Android 12/13. I've seen that you've put together kernels for nethunter on Android 12/3 though and I'm at a a loss as to how this contradiction can be resolved. Any guidance will be appreciated :)

so, what's stopping you from installing the busybox? you can easily install osmosis's busybox within magisk.
